packages:
  # Applications
  - 'apps/*'

  # Packages partagés
  - 'packages/*'

  # Infrastructure (optionnel, si configs partagées)
  - 'infrastructure/*'

  # Tools (optionnel, si packages utilitaires)
  - 'tools/*'
