/**
 * Morphic Engine types
 */

import type {
  DesignHumainType,
  DesignHumainAutorite,
  NeurodivergenceType,
  MorphicProfile,
} from '@shinkofa/types';

/**
 * UI/UX preferences generated by the morphic engine
 */
export interface MorphicPreferences {
  // Visual
  theme: 'light' | 'dark' | 'auto';
  fontSize: 'small' | 'medium' | 'large';
  contrastMode: boolean;
  colorScheme: 'default' | 'warm' | 'cool' | 'monochrome';

  // Layout
  spacing: 'compact' | 'normal' | 'comfortable';
  density: 'low' | 'medium' | 'high';
  layoutStyle: 'grid' | 'list' | 'cards';

  // Interactions
  reducedMotion: boolean;
  animationSpeed: 'slow' | 'normal' | 'fast';
  hapticFeedback: boolean;
  soundEffects: boolean;

  // Navigation
  navigationStyle: 'sidebar' | 'tabs' | 'bottom';
  quickAccess: boolean;
  breadcrumbs: boolean;

  // Cognitive Load
  showHelperText: boolean;
  progressIndicators: boolean;
  visualCues: boolean;
  stepByStepMode: boolean;

  // Energy Management
  optimalHours: string[]; // ["08:00", "09:00", ...]
  lowEnergyHours: string[]; // ["14:00", "15:00", ...]
  breakReminders: boolean;
  energyTracking: boolean;
}

/**
 * Morphic recommendations based on profile analysis
 */
export interface MorphicRecommendations {
  // Design Humain specific
  decisionMakingGuidance: string;
  interactionStyle: string;
  communicationPreferences: string;

  // Neurodivergence specific
  cognitiveSupport: string[];
  sensoryConsiderations: string[];
  focusStrategies: string[];

  // General
  workStyle: string;
  energyManagement: string;
}

/**
 * Complete morphic adaptation
 */
export interface MorphicAdaptation {
  profile: MorphicProfile;
  preferences: MorphicPreferences;
  recommendations: MorphicRecommendations;
  lastUpdated: Date;
}
