"""
from app.services.markdown_generator import MarkdownGenerator
Report Service - Generate and manage reports
"""

import json
from datetime import datetime
from typing import Optional, List
from sqlalchemy.orm import Session
from sqlalchemy import desc

from app.models.report import Report
from app.models.user import User, UserRole
from app.models.exercise import ExerciseScore
from app.schemas.report import ReportCreate, ReportGenerateRequest


class ReportService:
    """Service for report generation and management"""
    @staticmethod
    def generate_analytics_report(
        db: Session,
        user: User,
        request: ReportGenerateRequest
    ) -> Report:
        """Generate analytics report in Markdown format (Obsidian-optimized)"""
        # Generate Markdown content using MarkdownGenerator
        markdown_content = MarkdownGenerator.gen_analytics(db, user, request.parameters)
        
        # Create report title
        title = request.title or f"Rapport Analytics - {datetime.utcnow().strftime('%d/%m/%Y %H:%M')}"
        filename = f"SLF-Analytics-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}.md"
        
        # Store parameters
        parameters = json.dumps(request.parameters or {})
        
        # Calculate file size
        file_size = len(markdown_content.encode('utf-8'))
        
        # Create report record with generated content
        report_data = ReportCreate(
            title=title,
            report_type=request.report_type,
            format=request.format,
            filename=filename,
            file_size=file_size,
            file_path=None,  # Not storing files on disk
            content=markdown_content,  # Generated Markdown content
            parameters=parameters
        )
        
        report = Report(
            **report_data.dict(),
            generated_by_id=user.id,
            generated_at=datetime.utcnow(),
            is_available=True
        )
        
        db.add(report)
        db.commit()
        db.refresh(report)
        
        return report

    @staticmethod
    def get_user_reports(
        db: Session,
        user_id: int,
        report_type: Optional[str] = None,
        skip: int = 0,
        limit: int = 50
    ) -> List[Report]:
        """Get reports generated by a user"""
        query = db.query(Report).filter(
            Report.generated_by_id == user_id,
            Report.is_available == True
        )

        if report_type:
            query = query.filter(Report.report_type == report_type)

        reports = query.order_by(desc(Report.generated_at)).offset(skip).limit(limit).all()
        return reports

    @staticmethod
    def get_all_reports(
        db: Session,
        report_type: Optional[str] = None,
        skip: int = 0,
        limit: int = 50
    ) -> tuple[List[Report], int]:
        """Get all reports (managers/admins only)"""
        query = db.query(Report).filter(Report.is_available == True)

        if report_type:
            query = query.filter(Report.report_type == report_type)

        total = query.count()
        reports = query.order_by(desc(Report.generated_at)).offset(skip).limit(limit).all()

        return reports, total

    @staticmethod
    def get_report_by_id(db: Session, report_id: int) -> Optional[Report]:
        """Get a specific report by ID"""
        return db.query(Report).filter(
            Report.id == report_id,
            Report.is_available == True
        ).first()

    @staticmethod
    def delete_report(db: Session, report_id: int, user_id: int) -> bool:
        """Soft delete a report (mark as unavailable)"""
        report = db.query(Report).filter(
            Report.id == report_id,
            Report.generated_by_id == user_id,
            Report.is_available == True
        ).first()

        if not report:
            return False

        report.is_available = False
        db.commit()
        return True

    @staticmethod
    def get_report_stats(db: Session, user_id: Optional[int] = None) -> dict:
        """Get report generation statistics"""
        query = db.query(Report).filter(Report.is_available == True)

        if user_id:
            query = query.filter(Report.generated_by_id == user_id)

        total_reports = query.count()

        # Count by type
        analytics_count = query.filter(Report.report_type == "analytics").count()
        progression_count = query.filter(Report.report_type == "progression").count()
        attendance_count = query.filter(Report.report_type == "attendance").count()
        exercises_count = query.filter(Report.report_type == "exercises").count()

        # Count by format
        markdown_count = query.filter(Report.format == "markdown").count()
        pdf_count = query.filter(Report.format == "pdf").count()
        csv_count = query.filter(Report.format == "csv").count()
        excel_count = query.filter(Report.format == "excel").count()

        return {
            "total_reports": total_reports,
            "by_type": {
                "analytics": analytics_count,
                "progression": progression_count,
                "attendance": attendance_count,
                "exercises": exercises_count,
            },
            "by_format": {
                "markdown": markdown_count,
                "pdf": pdf_count,
                "csv": csv_count,
                "excel": excel_count,
            }
        }
